### ISSUE TITLE
Some behaviors differ from vanilla Ember 

### ISSUE THREAD

**Issue by jacobq** [ember-decorators/ember-decorators#334] opened 2018-12-07 17:13 UTC
I've been using `ember-decorators` throughout my app and for the most part it seems to work fine. However, occasionally I encounter a case where switching from the old/standard way of defining computed properties or macros causes something to quit working. 

I suspect this has something to do with either attempting (perhaps subtly) to nest `@each` or when in the object's lifecycle the computed property is applied. I've created [this ember-twiddle to show the problem](https://ember-twiddle.com/20e7b2961924ef89e86b5d5557ff1d3e?openFiles=controllers.application.js%2C). Please take a look and let me know if this is bug with `ember-decorators`. I'm not sure why this is happening or what I should do about it (other than revert to the old way of doing it in problematic cases).

```js
import EmberObject from '@ember/object';
import { alias as oldAlias } from '@ember/object';
import { alias } from '@ember-decorators/object';

class ParentItem extends EmberObject.extend({
  isSelected: oldAlias('child.isSelected') // works
}) {
  @alias('child.isSelected') isSelected2; // doesn't work ??
}
```

**Comment by pzuraq** [comment] 2018-12-07 18:14
Hey @jacobq, sorry you're having these difficulties! I tried to reproduce on the latest Ember, v3.6, which is the first release of Ember to officially support native class syntax (as in, the behavior has stabilized), and it appears to be working. You can polyfill this behavior with the native class polyfill back to Ember 3.4:

```
ember install ember-native-class-polyfill
```

As an aside, while zebra striping _should_ work as you've laid out, we _highly_ discourage using it in actual apps and will be adding a lint rule against it soon. The only thing that should go in an anonymous extend is mixins:

```js
// bad
class Foo extends EmberObject.extend({
  bar: 'baz'
}) {

}

// good
class Foo extends EmberObject.extend(BarMixin) {

}
```

**Comment by jacobq** [comment] 2018-12-07 18:50
> You can polyfill this behavior with the native class polyfill back to Ember 3.4:

Oh, I am using 3.5 and thought `ember-decorators` took care of all the polyfilling automatically 😨 
Maybe that's part of my problem....

> ...while zebra striping *should* work ...

What is "zebra striping"?

What is the recommended alternative to the following? Use an `@alias` on each `thing`?
```js
@computed('things.@each.prop.nestedProp') // <-- 
get aggregateProp() { ... }
```

**Comment by pzuraq** [comment] 2018-12-07 20:10
Zebra striping is going back and forth between native classes and classic classes (using `.extend()`). This should work in all cases, but again it’s not recommended to do this for defining a _single_ class. It’s perfectly ok to extend from a native class using classic class syntax and vice versa, but doing it in one class definition is an antipattern.

And yeah, since the native class behavior _just_ landed, we can’t add it to ember-decorators without a breaking change.

For the `@each` thing, I believe you’re trying to do with chains doesn’t work in vanilla Ember anymore either, and yes you should add a property that aliases it.

**Comment by pzuraq** [comment] 2019-01-11 18:31
Closing this issue, let me know if you have any further questions!

**Closed by pzuraq** 2019-01-11 18:31 UTC
