### ISSUE TITLE
Can't use old {inject as service} from ... with ember-decorators

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-decorators/ember-decorators#249] opened 2018-06-26 02:23 UTC
I've been chasing down a plethora of `Assertion Failed: InjectedProperties should be defined with the inject computed property macros.` errors.

Everything was already an ES6 class, and using `ember-cli-typescript`.
They were using the old `myService: service();` import
Only migrating **every** one of them to `@service myService` has removed the error.

**Comment by pzuraq** [comment] 2018-06-26 06:31
I’m not sure exactly what the issue is here. Can you post the old code and the new code?

Using `service()` directly from Ember on native classes has never been public API. It amy have worked before somehow, and internal changes in Ember could have broken that.

**Comment by rwjblue** [comment] 2018-06-26 11:59
I doubt the issue here is with ember-decorators, but we will need more information to be certain.

How were you using the non-decorator form before? What Ember version? What change introduced the error?

**Comment by mike-north** [comment] 2018-06-30 07:36
@rwjblue I ran into this when helping to upgrade up an ember app (already makes broad use of ember-decorators) from 2.17 to 3.1.0. Given the level of difficulty to track this down, we may want to include the `_debugContainerKey` of the object in question (and name of relevant property) whenever throwing this error.

Looks like the result of following a pattern like
```ts
import { inject as service } from '@ember/service';

export default class Foo extends Component {
  public bar = service();
}
```

which should be replaced by 

```ts
import { service } from 'ember-decorators/service';

export default class Foo extends Component {
  @service public bar;
}
```

**Comment by rwjblue** [comment] 2018-06-30 09:42
Yes, we should definitely make the assertion more actionable.

**Comment by BryanCrotaz** [comment] 2018-06-30 11:07
And the documentation for 3.2 shows the incorrect way of doing it.

https://guides.emberjs.com/release/applications/dependency-injection/#toc_ad-hoc-injections

I think we're saying that this will never work in Ember 3? I wasn't getting a deprecation in Ember 2.18

**Comment by BryanCrotaz** [comment] 2018-06-30 11:07
And it should be reasonably easy to build a codemod (although I've never built one, so...)

**Comment by pzuraq** [comment] 2018-06-30 15:00
Breaking it down, what's happening here is that `inject as service` return a computed property descriptor. When you pass a descriptor to `EmberObject.extend`, Ember applies the descriptor when extending the class itself, and sets up a bunch of things. When you use `class extends` syntax though, it works very differently. It is going to create a new computed property per _instance_ of the class, and set it directly on the instance, and Ember knows nothing about the descriptor until the first time you try to `get` it.

Before 3.1 this technically worked, because everyone used `.get` and computed properties were just set on the object. After 3.1, native getters were introduced, and that meant that Ember _had_ to intervene somehow. This is what the `@service` decorator does, it defines it just like if you had passed the computed to `EmberObject.extend`.

There _was_ a brief period where this was a common pattern among TS users, because ember-decorators did not work with TS. We always recommended against it, but it was hard to expect folks to move forward without an alternative 😕

Anyways, the two supported forms of computeds/injecting properties are:

```js
import { inject as service } from '@ember/service';

EmberObject.extends({
  service: service()
});
```
```js
import { service } from '@ember-decorators/service';

class MyClass extends EmberObject {
  @service service;
}
```

I think the assertion in Ember can be updated to say something more like the computed property assertion:

```
[DEPRECATED] computed property '${keyName}' was not set on object '${toString(obj)}' via 'defineProperty'
```

And maybe make a note on native classes?

**Comment by mike-north** [comment] 2018-06-30 17:21
An easy OSS contribution would be to fix the "every instance gets its own CP" pattern in the ember-cli-typescript readme. Lots of folks are repeating this

https://github.com/typed-ember/ember-cli-typescript#service-and-controller-injections

**Comment by pzuraq** [comment] 2018-06-30 18:34
@mike-north did not realize TS folks were still actively recommending that pattern, we def need to get that updated!

**Comment by BryanCrotaz** [comment] 2018-06-30 21:35
@rwjblue - not very different, the intent is the same, but it's not clear that you should code it differently if you're heading down the shiny ES6 road.

@pzuraq’s comment brings clarity to the issue. Trouble is this falls between the cracks between ES6 classes in Ember, `ember-decorators` and `ember-cli-typescript` (which is MUCH easier if you go with ES6 from the get-go). This drops the dev in a hole and because it's the combination of all three packages, it's not clear where to go to find out how you should be doing it.

My suggestion would be to modify the documentation in https://guides.emberjs.com/release/applications/dependency-injection/#toc_ad-hoc-injections to show both ways of doing it, clearly labelled for `EmberObject` and `ES6 class` and which way you should do it for each. I'd be happy to submit a PR for this. We should probably put something similar in the `ember-cli-typescript` docs.

**Comment by BryanCrotaz** [comment] 2018-06-30 23:28
Added PRs for documentation in `ember-cli-typescript` and `ember guides`

**Comment by BryanCrotaz** [comment] 2018-07-01 00:10
But the guides as they are don't cover ES6 which is touted as the clean way to use Ember 3. If you use ES6 and Ember 3, the examples in the guides simply won't compile.

**Comment by BryanCrotaz** [comment] 2018-07-01 00:11
I think `productive` wins over `strictly perfect` - I lost a week by following the guides and getting cryptic compile errors.

**Comment by pzuraq** [comment] 2018-07-01 00:13
ES6 is not yet officially recommended anywhere in the guides, specifically because we’re still working these details out. This is still the cutting edge, and we don’t want to jump the gun and begin recommending this as the standard path forward until all of the kinks have been worked out.

Believe me, I really want to update the guides too! This is a long term goal of mine, and we’re working hard to get to a point where it can be recommended as the standard for everyone, but it’s not there quite yet. Officially, using `EmberObject.extend` is still the recommended path for most users, especially those that prioritize stability.

**Comment by BryanCrotaz** [comment] 2018-07-01 00:15
The guides might not but lots of other people are (https://medium.com/build-addepar/es-classes-in-ember-js-63e948e9d78e). When you get an obscure compile error you go to the guides to check you're using Ember correctly.

**Comment by BryanCrotaz** [comment] 2018-07-01 00:17
So what should we say here?

> You can't use service injection in ES6 classes - there's a way to make it work, but we've decided we can't tell you about it because it's a 3rd party library, written by core Ember contributors. Good luck!

**Comment by BryanCrotaz** [comment] 2018-07-01 00:18
> This is still the cutting edge, and we don’t want to ... begin recommending this as the standard path forward

We're not - we're saying "here's the correct way for Ember Objects if you're using those" and "here's the correct way if you're using the new ES6 classes"

**Comment by BryanCrotaz** [comment] 2018-07-01 00:35
Added a note about ES6 to the guides PR

**Comment by pzuraq** [comment] 2018-07-01 00:45
Ember has always been very conservative about recommending new patterns, especially those that are not actually part of the Ember API. The reasoning behind this is we don’t want to misguide users, because eventually those things may become public API, and they may change in the process.

I think the best example of the migration path here is `ember-native-dom-helpers`. It was an excellent library, but it was not officially part of Ember, so we couldn’t rewrite the official guides. That was actually a good thing, because they did change when they were RFC’d as the official test helpers.

It is still possible for:

A. Decorators to change fundamentally in the TC39 process
B. The implementation of decorators in Ember to change once they are RFC’d into Ember.

To be clear, `ember-decorators` is stable and will not be changing. It’s just an awkward position for Ember - either recommend the cutting edge library which could incur a future upgrade cost, or wait and make it harder for early adopters 😕

I think the middle ground here is to really step up the documentation for new third party libraries, like ember-decorators and ember-cli-typescript, until the new path is fully baked and ready for mass adoption. 

That said, I agree there is an argument for making the main ember guides more comprehensive when covering cutting edge features, and get the frustration here. I think it’s a fundamental value shift for Ember we’re talking about though, so it’ll probably have to be discussed with the core teams and in the community (possibly via RFC)

**Comment by BryanCrotaz** [comment] 2018-07-01 01:03
Then separate the "here's how Ember API works" from "here's some companion projects that are stable and work". But if we don't include this general "building an app from multiple pieces" stuff then it falls down the cracks and everyone says "that's not part of our project, it's only relevant when you use our API with someone else's". Then we end up in the place we're in where it's essentially undocumented and major compile errors are impossible to fix. In my case, 2 days to write a working HTML editor with live data injection in Ember ES6 and 5 days to get it to build. I still haven't got the css to work anywhere but the dummy app. All this simply because the error falls outside the recommended scope of each individual project, so google doesn't help you find the problem.

I had a similar problem with a C level bug in ember-browserify with Ember 3. Impossible to debug, and after days of searching I found a competing library that didn't exhibit the error. Again there should be a recommended way to bring in third party npm libraries. It doesn't need to be part of Ember API to be part of "here's how to be productive". 

Ember shouldn't need to try and solve 100% of the problem. It should be fine to point users at other useful libraries which make them productive. If they're not stable, then warn during the pointing. But don't just ignore that they exist - that just frustrates people trying to get an app to work.

**Comment by pzuraq** [comment] 2018-07-01 01:10
Yup, like I said I totally agree this is a valid perspective. It just represents a fundamental value shoft for the framework, so you should probably continue the conversation with the core teams (especially the learning team) and see how to get the rest of the community on board.

**Comment by pzuraq** [comment] 2018-07-20 18:21
Going to close this issue for now, feel free to follow up with the Ember learn team

**Closed by pzuraq** 2018-07-20 18:21 UTC
