### ISSUE TITLE
v5.2 MS Edge 18: Object doesn't support property or method 'apply'

### ISSUE THREAD

**Issue by mfeckie** [ember-decorators/ember-decorators#417] opened 2019-03-18 09:45 UTC
We've encountered a failure case with ember-decorators in combination with ember-cli-typescript@1.5.0

The error does not happen in Edge 17 or any other browser that we've seen.

`Object doesn't support property or method 'apply'` is the error and cause the app not to boot.  We've been able to reproduce in two seperate codebases.

The error seems to occur at https://github.com/ember-decorators/ember-decorators/blob/master/packages/utils/addon/decorator.js#L89

The item returned by `decorate(fn)` is not correctly defined for some reason.

I've put together a repo with a reproducible failure case and detailed all the information I've found form poking about so far, in the README.

https://github.com/mfeckie/decorator-edge-repro

I don't have sufficient knowledge of the internals of decorators to be able to offer a fix, but happy to help with more information as necessary.

**Comment by mike-north** [comment] 2019-03-22 16:40
Now that `ember-cli-typescript@2` has been released, and decorators are transformed the same way regardless of whether original source is JS or TS, this should be re-evaluated.

@mfeckie can you upgrade `e-cli-ts` and let us know whether this Edge issue still exists?

**Comment by mfeckie** [comment] 2019-03-22 23:37
This is not an issue when using e-cli-ts@2, only on 1.5

We've migrated our codebase to use 2.x now, so the problem is gone for us, but it was a non trivial feat to upgrade because we also had to convert everything to use decorators (computeds and tasks).

**Comment by mike-north** [comment] 2019-03-23 01:03
Since this is fixed in 2.0 and would likely require some significant digging into legacy ember-cli-typescript and ember-decorators versions, I'll mark this as "won't fix". 

If we can identify that a lot of folks are affected by this, we can absolutely reopen this bug and evaluate a 1.x patch

**Comment by mfeckie** [comment] 2019-04-12 05:33
Getting this issue again, but this time it's with ECTS@2.x

**Comment by pzuraq** [comment] 2019-04-12 05:38
Can you add which versions of `ember-decorators` and the babel transforms you're using? I'd recommend getting off the stage 2 transforms, and updating to v6, using the polyfill. The stage 1 transforms packaged with `ember-cli-babel` could help.

**Comment by mfeckie** [comment] 2019-04-12 05:54
Will give it a trry

**Comment by mfeckie** [comment] 2019-04-12 06:06
If I remove the transforms, I can't get the server to start because it seems to break `ember-concurrency-decorators`.


I'm on `ember-decorators` v6
`ember-cli-babel` 7.7.3

**Comment by donaldwasserman** [comment] 2019-04-24 19:17
So I'm experiencing this issue, and like @mfeckie, I don't really see way out of this, because I can't quite figure out the matrix of: 

- `ember-decorators`
- `ember-cli-typescript`
- `ember-cli-babel-polyfills` 

that work to solve this problem. 

Using 
-`ember-decorators` `6.0.0`
- `ember-cli-babel` `7.7.3`
- `ember-concurrency-decorators` `0.6.0`
- No `@ember-decorators/babel-transforms`

Gets the server to start, but errors whenever the app comes across the first decorators.

**Comment by buschtoens** [comment] 2019-04-24 19:26
> No @ember-decorators/babel-transforms

Currently on mobile, but please use the latest e-c-d beta. It's compatible with stage 1 decorators.

**Comment by buschtoens** [comment] 2019-04-25 12:17
lol, I'm now also running into this bug, with the latest and greatest of all dependencies.

**Comment by buschtoens** [comment] 2019-04-25 12:36
I found the cause. 

https://github.com/ember-decorators/ember-decorators/blob/f3e3d636a38d99992af326a1012d69bf10a2cb4c/packages/utils/addon/decorator.js#L69-L78

L73 gets transpiled to:

```ts
return decorator(fn).apply(void 0, params);
```

`decorator(fn)` appears to return something weird that is logged as `[object Function]`. Inspecting that thing shows that it's prototype is set to `Object`. You can achieve this manually via `Object.setPrototype(function() {}, Object.prototype)`.

I don't know yet, why this only happens for Edge and not for any other browser. I would assume that it's a bug somewhere between ember-concurrency-decorators and ember-decorators. I'll dig further.

**Comment by buschtoens** [comment] 2019-04-25 12:50
Okay, it's broken in ember-decorators. I checked out `v5.2.0`, enabled the IE 11 browser in `targets.js` and tried running the test suite. It fails with the same error.

Since I personally can't switch to stage 1 / legacy decorators just yet in all applications I maintain (and others as well), I have a vested interest in fixing this. 😄

**Comment by donaldwasserman** [comment] 2019-04-25 12:51
@buschtoens - I don't understand how the underlying transpilation works (however, I am happy to make uninformed guesses!), but this is the exact same behavior I see. 

To add some more confusion, this bug **only** happens on edge 18 (edge 17 and 16 work as intended). 

I'm not sure if this is helpful or not, but I don't think it's e-c-decorators, since we don't have any of those in parts of the app that are initially throwing the error.

**Comment by donaldwasserman** [comment] 2019-04-25 12:53
@buschtoens Just saw your latest comment. I'd be happy to help/test things out in whatever way I can. I suspect like you, I've coded myself into a corner and this is the only way out.

**Comment by mfeckie** [comment] 2019-04-25 12:55
Not happy that others are having the same issue, but happy that some solutions may be in the pipeline 😄

**Comment by buschtoens** [comment] 2019-04-25 12:56
I'll keep reporting in `#e-decorators` to not wreck everybody's inboxes :D

**Comment by buschtoens** [comment] 2019-04-25 14:45
While we are waiting for #440 to be released, you can use the following hotfix. I'm not proud of that code, but I don't know an easier way to hack into the module system.

```js
/* eslint-disable no-global-assign, func-names, vars-on-top */

if (/Edge\/\d/.test(window.navigator.userAgent)) {
  (function(modDecorator, modFieldDescriptor) {
    var _define = window.define;
    window.define = function define(id, deps, callback) {
      _define(id, deps, callback);
      if (id === modDecorator) {
        window.define = _define;

        var mod = window.require(modDecorator);
        var _decorator = mod.decorator;
        var isDescriptor = window.require(modFieldDescriptor).isDescriptor;

        mod.decorator = function decorator(fn) {
          return Object.setPrototypeOf(_decorator(fn), Function.prototype);
        };

        mod.decoratorWithParams = function(fn) {
          return function() {
            var params = Array.prototype.slice.call(arguments);
            if (isDescriptor(params)) {
              return mod.decorator(fn).apply(undefined, params);
            }
            return mod.decorator(function(desc) {
              return fn(desc, params);
            });
          };
        };
      }
    };
  })(
    '@ember-decorators/utils/decorator',
    '@ember-decorators/utils/-private/class-field-descriptor'
  );
}
```

```js
// ember-cli-build.js
const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  const app = new EmberApp(defaults, {});
  app.import('vendor/decorators-hotfix.js');
  return app.toTree();
};
```

**Comment by mfeckie** [comment] 2019-04-26 00:31
Nice work.  I can wait for the PR to be merged thankfully :)

**Comment by elgordino** [comment] 2019-08-16 09:11
Thank you for the hotfix @buschtoens, you saved my day!

**Closed** 2022-08-05 21:08 UTC
Labels: bug, 5.x
