### ISSUE TITLE
[BUG] instance properties are not defined in ES2015 classes init method

### ISSUE THREAD

**Issue by bartocc** [ember-decorators/ember-decorators#164] opened 2017-09-13 15:28 UTC
I have noticed that when using the ES2015 syntax for a class, instance properties are not available in the init method while there are available when using the standard MyClass.extends syntax:

# Good

```javascript
import Ember from 'ember';

export default Ember.Service.extend({
  foo: 'foo',

  init() {
    this._super(...arguments);

    if (this.get('foo') != 'foo') {
      throw('error');
    }

  }

});
```
# Bad

```javascript
import Ember from 'ember';

export default class extends Ember.Service {
  foo = 'foo'

  init() {
    super.init();

    if (this.get('foo') != 'foo') {
      throw('error');
    }
  }

}
```

# How to reproduce

- `git clone https://github.com/bartocc/ember-decorators-es2015-init-bug`
- `cd ember-decorators-es2015-init-bug`
- `yarn`
- `ember test`

13 tests out of 14 should pass

test 'Unit | Service | bad service: it exists' should fail

**Comment by buschtoens** [comment] 2017-09-13 16:22
Dupe of #123. This is kinda by design.

**Comment by pzuraq** [comment] 2017-09-13 16:26
Yeah, like @buschtoens pointed out the babel transform is placing class field initialization at the end of the constructor, so they necessarily won't be initialized by this point.

I'm diving into the [class fields spec](https://tc39.github.io/ecma262/#sec-prepareforordinarycall) at the moment though to verify this. Typescript actually has [the opposite behavior here](http://www.typescriptlang.org/play/index.html#src=class%20Foo%20%7B%0D%0A%20%20%20%20aClassField%20%3D%20%27some%20string%27%0D%0A%0D%0A%20%20%20%20constructor()%20%7B%0D%0A%20%20%20%20%20%20%20%20this.aClassField%20%3D%20%27not%20that%20string%27%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20foo%20%3D%20new%20Foo()%3B%0D%0Aalert(foo.aClassField)%3B), and we've found that Babel has been off the spec before while TS has been correct (see #162) so I think this could be Babel being wrong again actually, which would change a lot of things (and potentially require an update to the RFC?)

**Comment by pzuraq** [comment] 2017-09-13 19:35
So it does look like this is a bug in Babel. Class fields, from my reading of the spec and from TS/Babel 7 beta's transpilations, should occur at the beginning of the constructor OR immediately after the call to `super` if it's a subclass. This means that `props` will still need to be passed in/modified as described in the RFC, and you will _not_ have access to class field default values in the `init` hook (since it is triggered in the call to `super`), but you _will_ have access to them in the standard class constructor in the future.

Leaving this open as a reminder to upgrade babel asap

**Comment by mdconaway** [comment] 2018-01-19 11:48
As a temporary workaround, you can create your own "instance attribute" decorator in your project and use  the above property declaration style.  Here is an example code block that I have found to work:

```javascript
import collapseProto from '@ember-decorators/utils/collapse-proto';
import extractValue from '@ember-decorators/utils/extract-value';
import { decorator } from '@ember-decorators/utils/decorator-wrappers';

export const instanceAttr = decorator(function(target, key, desc) {
    const value = extractValue(desc);
    collapseProto(target);
    target[key] = value;
    return value;
});
```

You can then use this in your code like:
```javascript
import Component from '@ember/component';
import { instanceAttr } from 'my-project/util/decorators';

export default class MyComponent extends Component {
    @instanceAttr someProp = ['anything', 'you', 'want', 'here']
}
```

Does anyone think this decorator would be useful as an included decorator in `ember-decorators`?  If so, I would be happy to make a pull request to add this functionality.  I think it would fit well under the object decorators.

**Comment by pzuraq** [comment] 2018-01-19 17:12
We actually made a decorator that does this in `utility-decorators` but it looks like this strategy will no longer work with stage 3 decorators. They’ve been changed so that you _cannot_ place class fields on the prototype 😕

I also highly recommend that you don’t code using proto collapsing for other reasons. The nuances of class field placement are very complicated, and things that do work one way won’t work the other and vice-versa. It’s better to stay on instance path, between the work we’re doing in Ember and the new Babel transforms it should all be working well soon enough

**Comment by pzuraq** [comment] 2018-02-23 18:46
Going to close this issue for the time being, it's not clear when the stage 2 version of decorators will land in Babel and I'd like to get the issue tracker cleaned up. Unfortunately this will be the accepted behavior for v1 and v2 of Ember Decorators, but v3 will come as soon as the transforms are updated and we're ready to upgrade!

**Closed by pzuraq** 2018-02-23 18:46 UTC

**Comment by bartocc** [comment] 2018-03-05 08:14
We'll wait for v3 then ;-)

We can work around this in the mean time. (see https://youtu.be/h-Zjym6sBvc?t=11m15s)

Maybe the readme should reference this issue though.
